# Generated by Django 5.0.3 on 2024-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoBooking', '0005_customuser_cle_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cle_paiement',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='paiement',
        ),
        migrations.AddField(
            model_name='commande',
            name='cle_paiement',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='paiement',
            field=models.BooleanField(default=False),
        ),
    ]
