# Generated by Django 5.0.3 on 2024-04-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoBooking', '0006_remove_reservation_cle_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='check_email',
            field=models.BooleanField(default=False),
        ),
    ]
