# Generated by Django 5.0.3 on 2024-04-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JoBooking', '0007_customuser_check_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='check_email',
            new_name='checked_email',
        ),
    ]
