# Generated by Django 5.0.3 on 2024-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoBooking', '0008_rename_check_email_customuser_checked_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='billet_pdf',
            field=models.FileField(blank=True, null=True, upload_to='billets/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
