# Generated by Django 5.0.3 on 2024-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoBooking', '0009_commande_billet_pdf_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='billet_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='billets/'),
        ),
    ]
