# Generated by Django 5.0.3 on 2024-05-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoBooking', '0010_alter_commande_billet_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='billet_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='billets/'),
        ),
    ]
